[project]
name = "skry-bun"
version = "0.1.0"
description = "Bun integration with python projects"
readme = "README.md"
authors = [
    { name = "Mike Oz", email = "kozloffsky@hotmal.com" }
]
requires-python = ">=3.13"
dependencies = [
    "typing-extensions>=4.12.2",
]
keywords = ["dependency-injection", "di", "fastapi", "starlette"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Framework :: AsyncIO",
    "Typing :: Typed",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/skry_bun"]
